=== exyorha/tesparse/DescriptionFiles/teslayout.dtd
<!ELEMENT Layout (RecordOrder,Types)>

<!ELEMENT RecordOrder (Header)>

<!ELEMENT Types (Struct|Record)*>

<!ELEMENT Header EMPTY>
<!ATTLIST Header
  Name CDATA #REQUIRED>

<!ELEMENT Struct (Field)*>
<!ATTLIST Struct
    Name CDATA #REQUIRED
>

<!ELEMENT Record (Subrecord|SubrecordArray)*>
<!ATTLIST Record
    FourCC CDATA #REQUIRED
    Name CDATA #REQUIRED
>

<!ELEMENT Field (FourCC|Int8|UInt8|UInt16|Int32|UInt32|Float|ByteArray|String|Array|StructRef)>
<!ATTLIST Field
  Name CDATA #REQUIRED>

<!ELEMENT Array (FourCC|Int8|UInt8|UInt16|Int32|UInt32|Float|ByteArray|String|Array|StructRef)>
<!ATTLIST Array
   Length CDATA #IMPLIED>

<!ELEMENT FourCC EMPTY>
<!ELEMENT Int8 EMPTY>
<!ELEMENT UInt8 EMPTY>
<!ELEMENT UInt16 EMPTY>
<!ELEMENT Int32 EMPTY>
<!ELEMENT UInt32 EMPTY>
<!ELEMENT Float EMPTY>

<!ELEMENT ByteArray EMPTY>
<!ATTLIST ByteArray
   Length CDATA #IMPLIED>

<!ELEMENT String EMPTY>
<!ATTLIST String
   Length CDATA #IMPLIED>

<!ELEMENT Subrecord (Field)*>
<!ATTLIST Subrecord
  FourCC CDATA #REQUIRED
  Presence (Required|Optional) #REQUIRED
>

<!ELEMENT SubrecordArray (Subrecord)*>
<!ATTLIST SubrecordArray
  Name CDATA #REQUIRED
  Leader CDATA #REQUIRED
>

<!ELEMENT StructRef EMPTY>
<!ATTLIST StructRef
  Name CDATA #REQUIRED
>

=== exyorha/tesparse/DescriptionFiles/morrowind.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE Layout SYSTEM "teslayout.dtd">
<Layout>
  <RecordOrder>
    <Header Name="Header" />
  </RecordOrder>

  <Types>

    <Struct Name="Record">
      <Field Name="Name">
        <FourCC />
      </Field>
      <Field Name="Size">
        <UInt32/>
      </Field>
      <Field Name="Flags1">
        <UInt32 />
      </Field>
      <Field Name="Flags2">
        <UInt32 />
      </Field>
      <Field Name="Data">
        <ByteArray Length="Size" />
      </Field>
    </Struct>

    <Struct Name="Subrecord">
      <Field Name="Name">
        <FourCC />
      </Field>
      <Field Name="Size">
        <UInt32 />
      </Field>
      <Field Name="Data">
        <ByteArray Length="Size" />
      </Field>
    </Struct>

    <Struct Name="MorrowindClassSkillPair">
      <Field Name="MinorSkill">
        <Int32 />
      </Field>
      <Field Name="MajorSkill">
        <Int32 />
      </Field>
    </Struct>

    <Struct Name="MorrowindSkillBonus">
      <Field Name="Skill">
        <Int32 />
      </Field>
      <Field Name="Bonus">
        <Int32 />
      </Field>
    </Struct>

    <Struct Name="MorrowindFactionRankInfo">
      <Field Name="AttributeRequirements">
        <Array Length="2">
          <UInt32 />
        </Array>
      </Field>
      <Field Name="SkillRequirements">
        <Array Length="2">
          <UInt32 />
        </Array>
      </Field>
      <Field Name="FactionRequirement">
        <UInt32 />
      </Field>
    </Struct>

    <Struct Name="MorrowindCreatureAttack">
      <Field Name="Min">
        <Int32 />
      </Field>
      <Field Name="Max">
        <Int32 />
      </Field>
    </Struct>

    <Struct Name="MorrowindAIData">
      <Field Name="Hello">
        <UInt8 />
      </Field>
      <Field Name="Unknown1">
        <UInt8 />
      </Field>
      <Field Name="Fight">
        <UInt8 />
      </Field>
      <Field Name="Flee">
        <UInt8 />
      </Field>
      <Field Name="Alarm">
        <UInt8 />
      </Field>
      <Field Name="Unknown2">
        <UInt8 />
      </Field>
      <Field Name="Unknown3">
        <UInt8 />
      </Field>
      <Field Name="Unknown4">
        <UInt8 />
      </Field>
      <Field Name="Flags">
        <UInt32 />
      </Field>
    </Struct>

    <Struct Name="MorrowindAIWanderPackage">
      <Field Name="Distance">
        <UInt16 />
      </Field>
      <Field Name="Duration">
        <UInt8 />
      </Field>
      <Field Name="TimeOfDay">
        <UInt8 />
      </Field>
      <Field Name="IdleChances">
        <Array Length="9">
          <UInt8 />
        </Array>
      </Field>
    </Struct>

    <Struct Name="MorrowindAIFollowEscortPackage">
      <Field Name="X">
        <Float />
      </Field>
      <Field Name="Y">
        <Float />
      </Field>
      <Field Name="Z">
        <Float />
      </Field>
      <Field Name="Duration">
        <UInt16 />
      </Field>
      <Field Name="Target">
        <String />
      </Field>
    </Struct>

    <Struct Name="MorrowindAITravelPackage">
      <Field Name="X">
        <Float />
      </Field>
      <Field Name="Y">
        <Float />
      </Field>
      <Field Name="Z">
        <Float />
      </Field>
    </Struct>

    <Struct Name="MorrowindSpellEffect">
      <Field Name="EffectID">
        <UInt16 />
      </Field>
      <Field Name="SkillID">
        <UInt8 />
      </Field>
      <Field Name="AttributeID">
        <UInt8 />
      </Field>
      <Field Name="Range">
        <UInt32 />
      </Field>
      <Field Name="Area">
        <UInt32 />
      </Field>
      <Field Name="Duration">
        <UInt32 />
      </Field>
      <Field Name="MagnitudeMinimum">
        <UInt32 />
      </Field>
      <Field Name="MagnitudeMaximum">
        <UInt32 />
      </Field>
    </Struct>

    <Struct Name="MorrowindPosition">
      <Field Name="PositionX">
        <Float />
      </Field>
      <Field Name="PositionY">
        <Float />
      </Field>
      <Field Name="PositionZ">
        <Float />
      </Field>
      <Field Name="RotationX">
        <Float />
      </Field>
      <Field Name="RotationY">
        <Float />
      </Field>
      <Field Name="RotationZ">
        <Float />
      </Field>
    </Struct>
    
    <Record FourCC="TES3" Name="Header">
      <Subrecord FourCC="HEDR" Presence="Required">
        <Field Name="Version">
          <Float />
        </Field>
        <Field Name="Unknown">
          <UInt32 />
        </Field>
        <Field Name="Author">
          <String Length="32" />
        </Field>
        <Field Name="Description">
          <String Length="256" />
        </Field>
      </Subrecord>
      <SubrecordArray Name="Masters" Leader="MAST">
        <Subrecord FourCC="MAST" Presence="Required">
          <Field Name="MasterFile">
            <String />
          </Field>
        </Subrecord>
        <Subrecord FourCC="DATA" Presence="Required">
          <Field Name="MasterFileSize">
            <UInt32  />
          </Field>
        </Subrecord>
      </SubrecordArray>
    </Record>

    <Record FourCC="GMST" Name="GameSetting">
      <Subrecord FourCC="NAME" Presence="Required">
        <Field Name="Name">
          <String />
        </Field>
      </Subrecord>
      <Subrecord FourCC="STRV" Presence="Optional">
        <Field Name="StringValue">
          <String />
        </Field>
      </Subrecord>
      <Subrecord FourCC="INTV" Presence="Optional">
        <Field Name="IntegerValue">
          <Int32 />
        </Field>
      </Subrecord>
      <Subrecord FourCC="FLTV" Presence="Optional">
        <Field Name="FloatValue">
          <Float />
        </Field>
      </Subrecord>
    </Record>

    <Record FourCC="GLOB" Name="GlobalVariable">
      <Subrecord FourCC="NAME" Presence="Required">
        <Field Name="Name">
          <String />
        </Field>
      </Subrecord>
      <Subrecord FourCC="FNAM" Presence="Required">
        <Field Name="VariableType">
          <String />
        </Field>
      </Subrecord>
      <Subrecord FourCC="FLTV" Presence="Required">
        <Field Name="DefaultValue">
          <Float />
        </Field>
      </Subrecord>
    </Record>

    <Record FourCC="CLAS" Name="CharacterClass">
      <Subrecord FourCC="NAME" Presence="Required">
        <Field Name="Name">
          <String />
        </Field>
      </Subrecord>

      <Subrecord FourCC="FNAM" Presence="Required">
        <Field Name="FriendlyName">
          <String />
        </Field>
      </Subrecord>

      <Subrecord FourCC="CLDT" Presence="Required">
        <Field Name="Attributes">
          <Array Length="2">
            <UInt32 />
          </Array>
        </Field>
        <Field Name="Specialization">
          <UInt32 />
        </Field>
        <Field Name="Skills">
          <Array Length="5">
            <StructRef Name="MorrowindClassSkillPair" />
          </Array>
        </Field>
        <Field Name="Flags">
          <UInt32 />
        </Field>
        <Field Name="AutoCalcFlags">
          <UInt32 />
        </Field>
      </Subrecord>

      <Subrecord FourCC="DESC" Presence="Required">
        <Field Name="Description">
          <String />
        </Field>
      </Subrecord>
    </Record>

    <Record FourCC="FACT" Name="Faction">
      <Subrecord FourCC="NAME" Presence="Required">
        <Field Name="Name">
          <String />
        </Field>
      </Subrecord>

      <Subrecord FourCC="FNAM" Presence="Required">
        <Field Name="FriendlyName">
          <String />
        </Field>
      </Subrecord>

      <SubrecordArray Name="Ranks" Leader="RNAM">
        <Subrecord FourCC="RNAM" Presence="Required">
          <Field Name="RankName">
            <String />
          </Field>
        </Subrecord>
      </SubrecordArray>

      <Subrecord FourCC="FADT" Presence="Required">
        <Field Name="Attributes">
          <Array Length="2">
            <Int32 />
          </Array>
        </Field>

        <Field Name="RankInfo">
          <Array Length="10">
            <StructRef Name="MorrowindFactionRankInfo" />
          </Array>
        </Field>

        <Field Name="Skills">
          <Array Length="6">
            <Int32 />
          </Array>
        </Field>

        <Field Name="Unknown1">
          <UInt32 />
        </Field>

        <Field Name="Flags">
          <UInt32 />
        </Field>
      </Subrecord>

      <SubrecordArray Name="Relations" Leader="ANAM">
        <Subrecord FourCC="ANAM" Presence="Required">
          <Field Name="OtherFactionName">
            <String />
          </Field>
        </Subrecord>
        <Subrecord FourCC="INTV" Presence="Required">
          <Field Name="Reaction">
            <Int32 />
          </Field>
        </Subrecord>
      </SubrecordArray>
    </Record>

    <Record FourCC="RACE" Name="Race">
      <Subrecord FourCC="NAME" Presence="Required">
        <Field Name="Name">
          <String/>
        </Field>
      </Subrecord>
      <Subrecord FourCC="FNAM" Presence="Required">
        <Field Name="FriendlyName">
          <String/>
        </Field>
      </Subrecord>
      <Subrecord FourCC="RADT" Presence="Required">
        <Field Name="SkillBonuses">
          <Array Length="7">
            <StructRef Name="MorrowindSkillBonus" />
          </Array>
        </Field>
        <Field Name="Attributes">
          <!--
            Strength
             Male
             Female
            Intelligence
            Willpower
            Agility
            Speed
            Endurance
            Personality
            Luck
           -->
          <Array Length="8 * 2">
            <Int32 />
          </Array>
        </Field>
        <Field Name="Height">
          <Array Length="2">
            <Float />
          </Array>
        </Field>
        <Field Name="Weight">
          <Array Length="2">
            <Float />
          </Array>
        </Field>
        <Field Name="Flags">
          <Int32 />
        </Field>
